### PR TITLE
Fixed some typos and reworked the Lua tutorial with up-to-date info.

### PR DESCRIPTION
**Pull request by matej-zajacik**

### CODE REVIEW

**Comment by endlesstravel** [comment]
Nice change, I don't remember why there are two `install` files. And, thanks your ! 👍

**Comment by matej-zajacik** [comment]
> Nice change, I don't remember why there are two `install` files. And, thanks your ! 👍

Thank you!

What do you mean by two install files?

**Comment by endlesstravel** [comment]
here:
image
These two documents seem to be the same content. I don't remember how I wrote them. 
😆

**Comment by matej-zajacik** [comment]
Oh that. :) Yeah, there are quite a few files that seem obsolete or stubs for perhaps planned documentation. I'll take a look at them and propose a clean up.

**Comment by endlesstravel** [comment]
ok, ha, i am alreay delet the `2.install.md` at `master`. don't worry, if you delete at `doc_improvement` as well, it will be merge automatically.

**Comment by matej-zajacik** [comment]
Understood.

**Pull request merged**
